hermes_make:
	 gcc -o ../bin/poseidon main.c getmac_inc.c -I/usr/local/include -I. -L/usr/local/lib -lwiringPi -lcurl -L/usr/lib/arm-linux-gnueabihf -lmysqlclient -lpthread -lz -lm -lrt -ldl -I/usr/include/mysql -DBIG_JOINS=1  -fno-strict-aliasing  -g
