#! /bin/sh

### BEGIN INIT INFO
# Provides: poseidon
# Required-Start: $all
# Required-Stop: $all
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: Poseidon tank monitor daemon startup script
### END INIT INFO

case "$1" in
  start)
	echo "STARTING poseiodn daemon"
	/home/pi/poseidon/bin/poseidon
	;;
  stop)
	echo "STOPPPING poseiodn daemon"
	pkill poseidon
	;;
  restart)
	echo "RESTARTING poseidon daemon"
	pkill -HUP poseidon
	;;
  *)
	echo "Usage: sh poseidon {start|stop}"
	;;
esac

exit 0

